package ru.mike.moviebot.statemachine.event;

public enum BotEvent {
    REACH_RANDOM, REACH_TOP, REACH_PARAM, REACH_LIST,
    REACH_GENRE_TOP, REACH_YEAR_TOP, REACH_RATING_TOP, REACH_NEW_LIST,
    REACH_GENRE_PARAM, REACH_YEAR_PARAM, REACH_RATING_PARAM, REACH_ACTOR_PARAM,
    REACH_CURRENT_GENRE_TOP, REACH_CURRENT_YEAR_TOP,
    REACH_CURRENT_GENRE_PARAM, REACH_CURRENT_YEAR_PARAM, REACH_CURRENT_RATING_PARAM, REACH_CURRENT_ACTOR_PARAM, REACH_FIND_PARAM_MOVIE,
    REACH_DROP_GENRE_PARAM, REACH_DROP_YEAR_PARAM, REACH_DROP_RATING_PARAM, REACH_DROP_ACTOR_PARAM,
    REACH_CONTINUE_GENRE, REACH_CONTINUE_YEAR, REACH_CONTINUE_RATING, REACH_CONTINUE_PARAM
}
