package ru.mike.moviebot.statemachine.state;

public enum BotState {
    NEW,
    RANDOM, TOP, PARAM, LIST,
    GENRE_TOP, YEAR_TOP, RATING_TOP, GENRE_PARAM, YEAR_PARAM, RATING_PARAM, ACTOR_PARAM, NEW_LIST,
    CURRENT_GENRE_TOP, CURRENT_YEAR_TOP, CURRENT_GENRE_PARAM, CURRENT_YEAR_PARAM, CURRENT_RATING_PARAM, CURRENT_ACTOR_PARAM, FIND_PARAM_MOVIE,
    DROP_GENRE_PARAM, DROP_YEAR_PARAM, DROP_RATING_PARAM, DROP_ACTOR_PARAM,
    CONTINUE_GENRE, CONTINUE_YEAR, CONTINUE_RATING, CONTINUE_PARAM,
    END
}
